version: '3.9'

services:
  postgres:
    image: "docker.io/library/postgres:13"
    container_name: apl-postgres
    environment:
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_DB=apl_db"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
volumes:
  postgres_data:

networks:
  default:
    name: apl-network
